// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/muhammadFittra/notification-service/internal/domain"
)

// ─────────────────────────────────────────────────────────────
// MockNotificationRepository
// ─────────────────────────────────────────────────────────────

// MockNotificationRepository is a mock of NotificationRepository interface
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

func (m *MockNotificationRepository) Save(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockNotificationRepositoryMockRecorder) Save(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotificationRepository)(nil).Save), ctx, n)
}

func (m *MockNotificationRepository) FindByID(ctx context.Context, id string) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockNotificationRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNotificationRepository)(nil).FindByID), ctx, id)
}

func (m *MockNotificationRepository) UpdateStatus(ctx context.Context, id string, status domain.DeliveryStatus, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockNotificationRepositoryMockRecorder) UpdateStatus(ctx, id, status, errMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateStatus), ctx, id, status, errMsg)
}

func (m *MockNotificationRepository) FindByUserID(ctx context.Context, userID string, limit, offset int) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockNotificationRepositoryMockRecorder) FindByUserID(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockNotificationRepository)(nil).FindByUserID), ctx, userID, limit, offset)
}

// ─────────────────────────────────────────────────────────────
// MockTemplateRepository
// ─────────────────────────────────────────────────────────────

type MockTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRepositoryMockRecorder
}

type MockTemplateRepositoryMockRecorder struct {
	mock *MockTemplateRepository
}

func NewMockTemplateRepository(ctrl *gomock.Controller) *MockTemplateRepository {
	mock := &MockTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockTemplateRepositoryMockRecorder{mock}
	return mock
}

func (m *MockTemplateRepository) EXPECT() *MockTemplateRepositoryMockRecorder {
	return m.recorder
}

func (m *MockTemplateRepository) FindByName(ctx context.Context, name string) (*domain.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*domain.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTemplateRepositoryMockRecorder) FindByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockTemplateRepository)(nil).FindByName), ctx, name)
}

// ─────────────────────────────────────────────────────────────
// MockUserRepository
// ─────────────────────────────────────────────────────────────

type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

func (m *MockUserRepository) FindContactByUserID(ctx context.Context, userID string) (*domain.UserContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContactByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.UserContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockUserRepositoryMockRecorder) FindContactByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContactByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindContactByUserID), ctx, userID)
}

// ─────────────────────────────────────────────────────────────
// MockEmailProvider
// ─────────────────────────────────────────────────────────────

type MockEmailProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEmailProviderMockRecorder
}

type MockEmailProviderMockRecorder struct {
	mock *MockEmailProvider
}

func NewMockEmailProvider(ctrl *gomock.Controller) *MockEmailProvider {
	mock := &MockEmailProvider{ctrl: ctrl}
	mock.recorder = &MockEmailProviderMockRecorder{mock}
	return mock
}

func (m *MockEmailProvider) EXPECT() *MockEmailProviderMockRecorder {
	return m.recorder
}

func (m *MockEmailProvider) Send(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailProviderMockRecorder) Send(ctx, to, subject, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailProvider)(nil).Send), ctx, to, subject, body)
}

// ─────────────────────────────────────────────────────────────
// MockPushProvider
// ─────────────────────────────────────────────────────────────

type MockPushProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPushProviderMockRecorder
}

type MockPushProviderMockRecorder struct {
	mock *MockPushProvider
}

func NewMockPushProvider(ctrl *gomock.Controller) *MockPushProvider {
	mock := &MockPushProvider{ctrl: ctrl}
	mock.recorder = &MockPushProviderMockRecorder{mock}
	return mock
}

func (m *MockPushProvider) EXPECT() *MockPushProviderMockRecorder {
	return m.recorder
}

func (m *MockPushProvider) Send(ctx context.Context, deviceToken, title, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, deviceToken, title, body)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPushProviderMockRecorder) Send(ctx, deviceToken, title, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPushProvider)(nil).Send), ctx, deviceToken, title, body)
}
