// Code generated by MockGen. DO NOT EDIT.
// Source: notification_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/muhammadFittra/notification-service/internal/domain"
)

// MockNotificationService is a mock of NotificationService interface
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockNotificationService) Send(ctx context.Context, req *domain.NotificationRequest) ([]*domain.NotificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req)
	ret0, _ := ret[0].([]*domain.NotificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send
func (mr *MockNotificationServiceMockRecorder) Send(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationService)(nil).Send), ctx, req)
}

// ProcessEvent mocks base method
func (m *MockNotificationService) ProcessEvent(ctx context.Context, event *domain.EventMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessEvent indicates an expected call of ProcessEvent
func (mr *MockNotificationServiceMockRecorder) ProcessEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockNotificationService)(nil).ProcessEvent), ctx, event)
}

// GetNotificationStatus mocks base method
func (m *MockNotificationService) GetNotificationStatus(ctx context.Context, notificationID string) (*domain.NotificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationStatus", ctx, notificationID)
	ret0, _ := ret[0].(*domain.NotificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationStatus indicates an expected call of GetNotificationStatus
func (mr *MockNotificationServiceMockRecorder) GetNotificationStatus(ctx, notificationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationStatus", reflect.TypeOf((*MockNotificationService)(nil).GetNotificationStatus), ctx, notificationID)
}
